import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { MainMenuComponent } from "@/components/main-menu.component";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio Semog Dev",
  description: "Generated by semog-dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.className} antialiased dark max-w-7xl mx-auto p-1 flex flex-col min-h-screen`}
      >
        <MainMenuComponent />
        <main className="flex-1">{children}</main>
        <footer className="flex justify-end items-end my-5">
          <p className="text-secondary">
            Este site foi desenvolvido por semog-dev
          </p>
        </footer>
      </body>
    </html>
  );
}
